package poitest;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohit.sareen
 */
public class CoverBrowse extends javax.swing.JDialog {

    /**
     * Creates new form CoverBrowse
     */
    public String filePath = null;
    public CoverBrowse(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final java.awt.Dimension screenSize = toolkit.getScreenSize();
        final int x = ( screenSize.width  - getWidth()  ) / 2;
        final int y = ( screenSize.height - getHeight() ) / 2;
        setLocation( x , y );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
      String command = evt.getActionCommand();
      if( command.equals(JFileChooser.APPROVE_SELECTION)) 
      {
          try 
          {
              File file = jFileChooser1.getSelectedFile();
              filePath = file.getCanonicalPath(); 
              this.dispose();
          }
          catch (Exception ex) 
          {
              JOptionPane.showMessageDialog( this , "ERRORS" ,
                          "Error:" +ex.toString() , JOptionPane.ERROR_MESSAGE );
          }
      }
      else if (command.equals(JFileChooser.CANCEL_SELECTION))
           this.dispose();
      else
           JOptionPane.showMessageDialog( this , "wrong selection" ,
                   "Error" , JOptionPane.ERROR_MESSAGE );
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
